on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: bitcomplete-oss-q2tc
          service_account_key: ${{ secrets.GCP_PUBLIC_ARTIFACT_WRITER_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev
      - run: docker build -t us-central1-docker.pkg.dev/bitcomplete-oss-q2tc/public/internal-rp:${GITHUB_REF#refs/tags/} -t us-central1-docker.pkg.dev/bitcomplete-oss-q2tc/public/internal-rp:latest .
      - run: docker push us-central1-docker.pkg.dev/bitcomplete-oss-q2tc/public/internal-rp:${GITHUB_REF#refs/tags/}
      - run: docker push us-central1-docker.pkg.dev/bitcomplete-oss-q2tc/public/internal-rp:latest
